name: Build and test
on: [push, pull_request]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool libc6-dev gettext libgtk2.0-dev libvorbis-dev
      
      - name: Build using makefile
        run: |
          autoreconf
          ./configure
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: cdrdao-ubuntu
          path: ./dao/cdrdao

  macos:
    name: Mac OS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Install dependencies
        run: |
          brew install autoconf automake libtool gettext vorbis-tools
      
      - name: Build using makefile
        run: |
          autoreconf
          ./configure
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: cdrdao-mac
          path: ./dao/cdrdao

  windows:
    name: Windows
    runs-on: windows-latest
    env:
      SHELLOPTS: igncr
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}

      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v4.0.1
        with:
          packages: autoconf automake libtool libiconv libgconf2 gcc-core libvorbis libao

      - name: Build using makefile
        run: |
          bash autoreconf
          bash ./configure
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: cdrdao-win
          path: ./dao/cdrdao-exe
